### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ghost** [ll3N1GmAll/ATAT#1]
Only way to talk to you but i have a question when using or installing atat can i put the folder anywhere and launch atat.sh or does it have to go somewhere specifically in order to work? also when i launch airgeddon it says this ::::: Launching Airgeddon!!:::::
                                                  bash: airgeddon: No such file or directory
hope to hear from you soon :) im testing out your software i added it to my custom distro :)

**Comment by ll3N1GmAll** [comment]
The readme directs users to place the ATAT folder in /root/ATAT for the greatest compatibility. The folder name MUST be in all caps like "ATAT". 

Run through the Dependency Checker to install airgeddon. If it exists in your distro's repo then you can run the basic dependency option to have it installed. If it doesn't exist in your repo then you will need to use the airgeddon install workaround option; but try the normal dependency option first.

**Comment by ghost** [comment]
My friend everything is in the read me like you said i should of read that first, thank you for the reply putting the folder in root everything works perfectly now.

**Comment by ll3N1GmAll** [comment]
No worries at all. We all jump into things excited at first and don't read the docs. I do it all the time too. :)

Glad to hear it is working for you and thank you for using the Attack Team Automation Tool!
